// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <WiFiMulti.h>

#define SECRET_SSID "NDF-Superfast"
#define SECRET_OPTIONAL_PASS "keineskeines"
#define SECRET_DEVICE_KEY "VSFHAZKQEO8ER4GX4AMD"

const char DEVICE_LOGIN_NAME[]  = "b2ffd33c-3015-4f01-b4b4-1d9030ba40e3";

const char SSID[]        = SECRET_SSID;    // Network SSID (name)
const char PASS[]        = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float voltage;
int bat_percentage;
int sensorValue; 

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(voltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bat_percentage, READ, ON_CHANGE, NULL);
  // ArduinoCloud.addProperty(bat_percentage, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS); // replaced with multififi
